# Generated by Django 5.0.6 on 2024-07-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='listing_status',
            field=models.BooleanField(default=True),
        ),
    ]
