# Generated by Django 5.0.6 on 2024-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlistings_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='listing_photo',
            field=models.URLField(blank=True, max_length=4000),
        ),
    ]
